### ISSUE TITLE
Develop (or copy) a style guide?

### ISSUE THREAD

**Issue by nstauffer** [JER-data-team/data.team#1]
I think part of what I was ineptly getting at on the phone was that we might want to not just have a code of conduct but some kind of style guide to help us keep our code mutually legible, *e.g.* naming conventions or when/where to use lists to store objects or values.

**Comment by smccord** [comment]
that makes sense to me! After we got off I actually wondered if we wanted to set some general file naming conventions anyway (e.g., date_name_blah). so let's do it! Do you know any resources we could tier from?

**Comment by nstauffer** [comment]
I think I have some squirrelled away, but I'll also ask some people I know at weecology (a group of freelance ecologists) and some other adjacent folks who I'm pretty sure have confronted exactly this before. Don't be surprised if you see a general broadcast on Twitter too!

**Comment by smccord** [comment]
I think I've seen something from them before too...great idea!

**Comment by nstauffer** [comment]
I've got multiple votes of support from a few ecology and non-ecology folks for using the [tidyverse style guide](https://style.tidyverse.org/) because it's comprehensive, R specific, and we'd already tossed around the idea of using lintr.

**Comment by smccord** [comment]
Beautiful. Let's do it!
